name: keras_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - keras=2.2.4
  - matplotlib
  - pandas
  - python=3.6
  - scikit-learn=0.21.2
  - scipy
  - seaborn
  - tensorflow=1.10.0
  - pip:
    - ushuffle==1.1.0